### PR TITLE
Add base for Lambda; doesn't work yet

### PR DESCRIPTION
**Pull request by NoMod-Programming**
Don't merge!
- [ ] Add GUI for lambda
- [ ] Rewrite interpreter to support lambda
- [ ] Add serializer for lambda blocks

### CODE REVIEW

**Comment by GRA0007** [comment]
I'm looking forward to this :D It looks really exciting. Ya I'm terrible at actionscript

**Comment by CosmicWebServices** [comment]
nice

**Comment by NoMod-Programming** [comment]
Thanks! I'vs been on vacation for the past two weeks, so I havent been able to work any more on this yet. I expect to be able to very soon, though

**Comment by GRA0007** [comment]
@NoMod-Programming That's fine, I have been really busy with school and lots of other stuff that's come up recently like my queen scout badge.

**Comment by NoMod-Programming** [comment]
@GRA0007 Cool! I just got on my computer, so I'm getting to work on this now.

**Comment by NoMod-Programming** [comment]
Gonna close this branch, and start from scratch (no pun intended). I've got some new ideas on how I'm going to implement this.

**Pull request closed without merging**
