### PR TITLE
Add Color Blocks

### PR DESCRIPTION
**Pull request by NoMod-Programming**
This pull request will add Color Blocks, fix the `<___ is a [number v]?>`, and fix building with `ant`

### CODE REVIEW

**Comment by GRA0007** [comment]
I use gradle to build it, but it would be good if people still on ant can build it without gradling. Thanks a lot for implementing the colour blocks! I've kinda been very busy with school and midterm exams and stuff, so I haven't had a lot of time to work on it. I reckon this can be the 1.1 beta release if you're ok with that, and I'll try and get the custom reporters working by totally no stealing code from [here](https://github.com/LLK/scratch-flash/pull/179). :smile:

**Comment by NoMod-Programming** [comment]
Actually, I've nearly got them implemented on me end. I'll submit a pull request in a few hours with them :)

**Comment by GRA0007** [comment]
Whaa, you're amazing (★ω★).

**Comment by NoMod-Programming** [comment]
Thanks!

**Pull request merged**
